# This is a basic workflow to help you get started with Actions

name: Gradle Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: -Ptag=${{github.ref_name}} shadowJar

    - name: GH Release
      uses: softprops/action-gh-release@v2
      with:
        files: "**/build/libs/*.jar"
